### ISSUE TITLE
关于导出公式的问题

### ISSUE THREAD

**Issue by wongqueng** [songyz0310/songyz-xlsx#1]
你好朋友！我们公式也有这个需求，用到了js-xlsx,导入的时候只有第一个sheet成功导入了公式，导出的时候公式全没了，不知道你有没有遇到这个问题

**Comment by songyz0310** [comment]
我只是阅读过一些关于导入解析的方法，导出的场景我们这边一般都是处理好数据，再导出来，

**Comment by songyz0310** [comment]
目前，关于多sheet这个场景，我们这里是没有的

**Comment by wongqueng** [comment]
> 目前，关于多sheet这个场景，我们这里是没有的

谢了！！
